flowchart TB
  %% Clients
  subgraph Client
    U[Frontend / Cliente]
  end

  %% Functions layer
  subgraph Functions
    API[portafolio-cv-api\nFunction App]
    WORKER[portafolio-cv-worker\nFunction App]
    NOTIF[portafolio-notifier\nFunction App]
    PAY[portafolio-payments\nFunction App]
  end

  %% Data
  subgraph Storage
    QUEUE[Storage Queue cv-requests]
    BLOB[Blob container pdfs]
  end

  COSMOS[Cosmos DB\nServerless]

  %% Flow
  U --> API
  API -->|read/hash| COSMOS
  API -->|enqueue| QUEUE
  QUEUE --> WORKER
  WORKER -->|pdf privado| BLOB
  WORKER -->|status/meta| COSMOS
  WORKER -->|invoke| NOTIF
  NOTIF -->|email/CRM| U
  NOTIF --> COSMOS
  API -.-> PAY

  %% Infra shared
  PLAN[App Service Plan F1]
  ID[User Assigned Managed Identity]
  API --- PLAN
  WORKER --- PLAN
  NOTIF --- PLAN
  PAY --- PLAN
  API --- ID
  WORKER --- ID
  NOTIF --- ID
  PAY --- ID

  classDef fn fill:#eef,stroke:#333,stroke-width:1px
  classDef data fill:#ffd,stroke:#333,stroke-width:1px
  class API,WORKER,NOTIF,PAY fn
  class QUEUE,BLOB,COSMOS data