name: "Terraform - Apply (main)"

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -var "prefix=main" -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
